### ISSUE TITLE
get_gmtime function throw compilaion error when using ARM_ONLINE_COMPILER or MBED IDE

### ISSUE THREAD

**Issue by Roietronics** [Avnet/mbedv5_azure_iot_sdk#25]
The alternate implementation of gmtime_r in the platform/agenttime.c file for use with the ARM ONLINE COMPILER  has the wrong return type.

The function signature is void gmtime_r(const time_t *timer, struct tm *timeptr);

The standard c language signature for this function is
struct tm *timeptr gmtime_r(const time_t *timer, struct tm *timeptr);  which is the function contain in the gcc c library. The retrun value being the pointer to tm struct which was passed in as the second argument in the call to the function

The get_gmtime function in the same file will compile and return a value with the gcc implementation of gmtime_r but will throw a compilation error with the ARM_ONLINE_COMPILER implementation

**Comment by jflynn129** [comment]
thanks for the information.  I took this implementation from https://github.com/feilipu/avrfreertos/blob/master/freeRTOS82x/lib_time/gmtime_r.c but didn't verify its conformance for standard c -- the problem with 'borrowing/using' open-source code. I couldn't run the entire program using the on-line compiler because back when I was working on this, the on-line compiler would not let you specify compiler flags (which I did with the toolchain_debug.json file in the companion program that uses this library.  Because of this on-line tool limitation, I was able to compile but never run the program using the on-line compiler so I just used the CLI instead.  If you have an open-source reference for gmtime_r that could replace this function, we could do that, just submit a pull request and I'll update it.
